workflows:
  ios-release-build:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.omerfaruk.cmfl12c
      vars:
        flutter: stable
        xcode: latest
        cocoapods: default
    scripts:
      - name: Upgrade to latest Flutter stable version
        script: |
          flutter upgrade
          flutter doctor
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Create export_options.plist for App Store
        script: |
          cat <<EOF > /Users/builder/export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadSymbols</key>
              <true/>
              <key>teamID</key>
              <string>S4BFF79U9Z</string> <!-- Update with your Apple Developer Team ID -->
            </dict>
          </plist>
          EOF
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=1 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      
