workflows:
  full-release:
    name: Android + iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.omerfaruk.cmfl12c"
    scripts:
      - name: Clean
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android AAB
        script: flutter build appbundle --release
      - name: Build iOS IPA
        script: flutter build ipa --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        key_id: YTURD3VPWU
        issuer_id: f3069b18-bd42-4134-96ad-aee21af1dbc4
        private_key: |
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQga3hjBAZOQ3sb5w5Q
          
          qUAvl9NSF2k0Wpqu6EXEPh5POUmgCgYIKoZIzj0DAQehRANCAARuFkTh3rImS+Uc
          
          BeCt+q1zGB8pVu9q9buocQZ2JcMgTLDkFbJFGKV+LweRF3JVJZCNc1M5bjqtjgIR
          
          isRcE+49
          -----END PRIVATE KEY-----
        submit_to_testflight: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
