workflows:
  full-release:
    name: Android + iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Clean
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Build Android (.aab)
        script: flutter build appbundle --release

      - name: Build iOS (.ipa)
        script: flutter build ipa --release

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        authentication: integration
        integration: appstore_connect  # <- sen Codemagic’te ne isim verdiysen onu yaz
        submit_to_testflight: true

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
        
