// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGSM_ElUfqfagZuA1_YmfDKcbJDWBjwhU',
    appId: '1:855026607539:web:7e2086f54a1243589a97c6',
    messagingSenderId: '855026607539',
    projectId: 'sudeninistedigioyun',
    authDomain: 'sudeninistedigioyun.firebaseapp.com',
    storageBucket: 'sudeninistedigioyun.firebasestorage.app',
    measurementId: 'G-ZCX8FQWVH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCog9EN1Wg123UQneckc8EssE90VmAS4cA',
    appId: '1:855026607539:android:6ad350cf0cd1aba09a97c6',
    messagingSenderId: '855026607539',
    projectId: 'sudeninistedigioyun',
    storageBucket: 'sudeninistedigioyun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnOLeQZtqib1oAXrTo7Yrl74YlgiwzbL8',
    appId: '1:855026607539:ios:6e155bfef2457d9a9a97c6',
    messagingSenderId: '855026607539',
    projectId: 'sudeninistedigioyun',
    storageBucket: 'sudeninistedigioyun.firebasestorage.app',
    iosClientId: '855026607539-cael6ku3kfuu8gq18ce3oivq7l0ablp6.apps.googleusercontent.com',
    iosBundleId: 'com.omerfaruk.cmfl12c',
  );
}
